language: php
php:
  - 5.4
  - 5.5
  - 5.6

install: composer install

before_script: wget http://downloads.atoum.org/nightly/mageekguy.atoum.phar
script: ./bin/atoum -bf tests/Bootstrap.php -d tests/unit/
